#include "PositionListFirstStageScenario.h"

#include <algorithm>

namespace etfdt::tests::position_list_first_stage {

std::vector<PositionListFirstStageScenario> firstStageScenarios()
{
    return {
        {
            "empty_ledger_ok",
            R"({"accountId":"ACC-DEMO-001","requestedOutputs":["positions","issues"]})",
            true,
            false,
            true,
            false,
            "OK",
            "OK",
            {},
            "positions empty",
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            "Future first stage may return an empty read-only PositionListResponse.",
        },
        {
            "single_buy_ok",
            R"({"accountId":"ACC-DEMO-001","portfolioId":"PF-DEMO-001"})",
            true,
            false,
            true,
            false,
            "OK",
            "OK",
            {},
            "one position with quantity and cost",
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            "Future first stage may support the controlled single BUY path.",
        },
        {
            "missing_market_price_warning",
            R"({"accountId":"ACC-DEMO-001","requestedOutputs":["positions"]})",
            true,
            false,
            true,
            false,
            "MARKET_PRICE_MISSING",
            "WARNING",
            {"MARKET_PRICE_MISSING"},
            "positions allowed with UNAVAILABLE valuation",
            true,
            true,
            false,
            true,
            false,
            true,
            true,
            false,
            "Future first stage must not fabricate marketValueText or unrealizedPnlText.",
        },
        {
            "multi_currency_unsupported_error",
            R"({"accountId":"ACC-DEMO-001","requestedOutputs":["positions"]})",
            true,
            false,
            true,
            false,
            "MULTI_CURRENCY_UNSUPPORTED",
            "ERROR",
            {"MULTI_CURRENCY_UNSUPPORTED", "FX_RATE_MISSING"},
            "partial positions only if no FX valuation is fabricated",
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            "Future first stage must reject unsupported multi-currency valuation.",
        },
        {
            "cash_facts_missing_degraded_or_unavailable",
            R"({"accountId":"ACC-DEMO-001","requestedOutputs":["positions"]})",
            true,
            false,
            true,
            false,
            "CASH_FACTS_SOURCE_UNAVAILABLE",
            "DEGRADED",
            {"DATA_SOURCE_MISSING", "CASH_FACTS_SOURCE_UNAVAILABLE"},
            "trade-facts-derived holdings only if explicitly degraded",
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            false,
            "Future first stage must not derive cash facts from snapshots.",
        },
        {
            "mapping_failure_error",
            R"({"accountId":"ACC-DEMO-001"})",
            true,
            false,
            true,
            false,
            "POSITION_LIST_MAPPING_FAILED",
            "ERROR",
            {"POSITION_LIST_MAPPING_FAILED"},
            "no positions",
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            "Future mapping failures must remain no-write and blocking.",
        },
        {
            "replay_unavailable_error",
            R"({"accountId":"ACC-DEMO-001"})",
            true,
            false,
            true,
            false,
            "REPLAY_NOT_AVAILABLE",
            "ERROR",
            {"REPLAY_NOT_AVAILABLE"},
            "no positions",
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            "Future AccountingEngine unavailable path must remain no-write.",
        },
        {
            "invalid_request_protocol_error",
            R"([])",
            false,
            false,
            true,
            false,
            "INVALID_REQUEST",
            "ERROR",
            {"INVALID_REQUEST"},
            "no positions",
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            "Future malformed request path must not call DataAccess or AccountingEngine.",
        },
        {
            "facts_query_unavailable_error",
            R"({"accountId":"ACC-DEMO-001"})",
            true,
            false,
            true,
            false,
            "DATA_SOURCE_MISSING",
            "ERROR",
            {"DATA_SOURCE_MISSING"},
            "no positions",
            true,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            "Future facts query unavailable path must remain no-write.",
        },
        {
            "unsupported_scenario_error",
            R"({"accountId":"ACC-DEMO-001","requestedOutputs":["unsupported"]})",
            true,
            false,
            true,
            false,
            "UNSUPPORTED_SCENARIO",
            "ERROR",
            {"UNSUPPORTED_SCENARIO"},
            "no positions unless a safe supported subset is explicit",
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            "Future first stage must guard unsupported scenarios rather than broaden scope.",
        },
    };
}

std::vector<FailureMatrixEntry> firstStageFailureMatrix()
{
    return {
        {"INVALID_REQUEST", true, true, false, true, false, "protocol failure for malformed JSON; otherwise domain payload", "Invalid request must not write."},
        {"REPLAY_NOT_AVAILABLE", true, true, false, true, false, "success=true when payload can be returned", "Replay unavailable must not write."},
        {"DATA_SOURCE_MISSING", true, true, false, true, false, "success=true with domain issue", "Missing source must not write."},
        {"CASH_FACTS_SOURCE_UNAVAILABLE", true, true, false, false, true, "success=true with degraded domain issue", "Cash facts gap may degrade positions only when explicit."},
        {"POSITION_LIST_MAPPING_FAILED", true, true, false, true, false, "success=true when payload can be returned", "Mapping failure must not write."},
        {"MARKET_PRICE_MISSING", true, true, false, false, true, "success=true with warning issue", "Valuation fields must remain UNAVAILABLE."},
        {"MULTI_CURRENCY_UNSUPPORTED", true, true, false, true, false, "success=true with blocking issue", "FX valuation must not be fabricated."},
        {"FX_RATE_MISSING", true, true, false, true, false, "success=true with blocking FX issue", "Missing FX rate must not write."},
        {"SQLITE_READONLY_OPEN_FAILED", true, true, false, true, false, "success=true if payload can be returned, otherwise protocol failure", "Read-only open failure must not write."},
        {"SQLITE_QUERY_FAILED", true, true, false, true, false, "success=true if payload can be returned, otherwise protocol failure", "Query failure must not write."},
        {"UNSUPPORTED_SCENARIO", true, true, false, true, false, "success=true with domain issue", "Unsupported scenarios must not broaden first-stage scope."},
    };
}

bool hasScenario(
    const std::vector<PositionListFirstStageScenario>& scenarios,
    const std::string& scenarioName)
{
    return std::any_of(
        scenarios.begin(),
        scenarios.end(),
        [&](const PositionListFirstStageScenario& scenario) {
            return scenario.scenarioName == scenarioName;
        });
}

bool hasFailureStatus(const std::vector<FailureMatrixEntry>& matrix, const std::string& status)
{
    return std::any_of(
        matrix.begin(),
        matrix.end(),
        [&](const FailureMatrixEntry& entry) {
            return entry.status == status;
        });
}

}  // namespace etfdt::tests::position_list_first_stage
