#pragma once

#include "ShellServices/ShellAccountingIssue.h"

#include <cstdint>
#include <string>
#include <vector>

namespace etfdt::shell_services {

struct ShellAccountingServiceRequest final {
    std::string actionName;
    std::string accountId;
    std::string portfolioId;
    std::string sourceFromTime;
    std::string sourceToTime;
    bool includeIssues = true;
    bool includeDebugMetadata = false;
    std::string calculationVersion;
    std::vector<std::string> requestedOutputs;
    int timeoutMs = 0;
    std::string strategyId;
    std::string strategyCode;
    std::string instrumentId;
    std::string instrumentCode;
    std::string instrumentType;
    std::string tradeSource;
    std::string side;
    std::int64_t quantity1e6 = 0;
    std::string reason;
    std::string source;
    std::string sourceSnapshotId;
    std::string sourceReplayId;
    std::int64_t draftId = 0;
    std::string authorization;
    bool riskChecked = true;
    bool riskBlocked = false;
    bool tradeDraftDisabled = false;
    bool confirmationDisabled = false;
    std::string securityCode;
    std::string tradeSide;
    std::string quantityUnits;
    std::string priceAmountMinor;
    std::string grossAmountMinor;
    std::string feeAmountMinor;
    std::string taxAmountMinor;
    std::string occurredAt;
    std::string sourceMemo;
    std::string requestId;
    std::string idempotencyKey;
    std::string previewStatus;
    std::string previewDigest;
    std::string schemaVersion;
    std::string acceptedAt;
    std::string importBatchLabel;
    std::string movementType;
    std::string amountMinor;
    std::string currency;
    std::string sourceReference;
    std::string importPayloadJson;
    int importTradeFactCount = 0;
    int importCashFactCount = 0;
    int importMarketPriceFactCount = 0;
    int importFxRateFactCount = 0;
    std::string portfolioReplayPayloadJson;
    std::string strategyRecommendationPayloadJson;
    std::string marketDataPayloadJson;
    std::string realDailyUsePayloadJson;
    std::string otcMapPayloadJson;
    std::string recommendationDigest;
    bool userConfirmed = false;
    std::string expiresAtUtc;
};

struct ShellAccountingImportPreviewDiagnostic final {
    std::string level;
    std::string code;
    std::string field;
    std::string sheetName;
    std::string rowId;
};

struct ShellAccountingImportPreviewFactSummary final {
    int tradeFactCount = 0;
    int cashFactCount = 0;
    int marketPriceFactCount = 0;
    int fxRateFactCount = 0;
};

struct ShellAccountingServiceResult final {
    std::string actionName;
    bool protocolSuccess = true;
    bool implemented = false;
    bool readOnly = true;
    bool writeEnabled = false;
    std::string payloadStatus;
    std::string dataQualityStatus = "UNAVAILABLE";
    bool hasRows = false;
    std::vector<ShellAccountingIssue> issues;
    std::vector<ShellAccountingIssue> warnings;
    std::vector<ShellAccountingIssue> errors;
    std::string rawPayload;
    bool timeout = false;
    bool transportError = false;
    bool protocolError = false;
    bool domainError = false;
    bool generatedTradeDraft = false;
    bool generatedTradeSuggestion = false;
    bool strategyExecuted = false;
    bool brokerOrderSubmitted = false;
    bool transactionCommitted = false;
    bool duplicateImportPrevented = false;
    bool idempotencyConflictRejected = false;
    bool idempotencyRequired = false;
    bool importPreviewAccepted = false;
    bool importPreviewRejected = false;
    std::vector<ShellAccountingImportPreviewDiagnostic> importPreviewDiagnostics;
    std::vector<std::string> importPreviewDiagnosticCodes;
    ShellAccountingImportPreviewFactSummary importPreviewFactSummary;
    bool portfolioReplayAccepted = false;
    bool portfolioReplayExecuted = false;
    int portfolioReplayPositionCount = 0;
    int portfolioReplayCashSummaryCount = 0;
    std::string portfolioReplayRealizedPnlText;
    std::string portfolioReplayUnrealizedPnlText;
    std::string portfolioReplayTotalFeeText;
    std::string portfolioReplayTotalMarketValueText;
    std::vector<std::string> portfolioReplayIssueCodes;
    bool strategyRecommendationAccepted = false;
    bool strategyRecommendationComputed = false;
    std::string strategyRecommendationActionCode;
    std::string strategyRecommendationActionLabel;
    std::string strategyRecommendationSourceCode;
    std::string strategyRecommendationSourceLabel;
    std::string strategyRecommendationReasonCode;
    std::string strategyRecommendationReasonLabel;
    std::string strategyRecommendationTierLabel;
    std::string strategyRecommendationTargetAmountText;
    std::string strategyRecommendationSuggestedQuantityText;
    std::string strategyRecommendationSuggestedAmountText;
    std::string strategyRecommendationNetCashImpactText;
    std::string strategyRecommendationFeeText;
    bool strategyRecommendationBaseProtectionPassed = false;
    bool strategyRecommendationCashLimitApplied = false;
    std::vector<std::string> strategyRecommendationIssueCodes;
    bool marketDataAccepted = false;
    bool marketDataRefreshEngineCreated = false;
    bool marketDataProviderContractCreated = false;
    bool marketDataProviderDisabled = false;
    bool marketDataStale = false;
    bool marketDataPartial = false;
    bool marketDataLiveProviderDisabledByDefault = true;
    bool marketDataLiveProviderDeferredForSafety = true;
    std::string marketDataInstrumentCode;
    std::string marketDataInstrumentType;
    std::string marketDataCurrentPriceText;
    std::string marketDataPreviousCloseText;
    std::string marketDataHistoricalHighText;
    std::string marketDataDisplayedHighText;
    std::string marketDataHistoricalHighDate;
    std::string marketDataDrawdownFromHighText;
    std::string marketDataPremiumDiscountText;
    std::string marketDataProviderSource;
    std::vector<std::string> marketDataIssueCodes;
    std::string realDailyUseDbPath;
    std::string realDailyUseDataSourceStatus;
    std::string realDailyUseMarketSourceStatus;
    std::string realDailyUseLastAutoRefreshTime;
    std::string realDailyUseCacheStatus;
    std::string realDailyUseRefreshFailureReason;
    std::string realDailyUseSummary;
    bool tradeDraftManualRecommendationFlowCreated = false;
    bool tradeDraftUserConfirmationRequired = false;
    bool tradeDraftEligible = false;
    bool tradeDraftDuplicate = false;
    bool tradeDraftIdempotencyConflict = false;
    bool tradeDraftIsNotOrder = true;
    bool tradeDraftSummaryFound = false;
    std::int64_t tradeDraftId = 0;
    std::string tradeDraftStatus;
    std::string tradeDraftSide;
    std::string tradeDraftInstrumentCode;
    std::string tradeDraftQuantityText;
    std::string tradeDraftAmountText;
    std::string tradeDraftNetCashImpactText;
    std::string tradeDraftSummary;
    std::vector<std::string> tradeDraftIssueCodes;
    bool otcMapPreviewAccepted = false;
    bool otcMapPreviewExecuted = false;
    int otcMapPreviewLegCount = 0;
    std::string otcMapPreviewStatus;
    std::string otcMapPreviewTotalAmountText;
    std::string otcMapPreviewSummary;
    std::vector<std::string> otcMapPreviewIssueCodes;
    bool otcMapDraftDuplicate = false;
    bool otcMapDraftIdempotencyConflict = false;
    std::int64_t otcMapDraftId = 0;
    int otcMapDraftLegCount = 0;
    std::string otcMapDraftStatus;
    std::string otcMapDraftSummary;
    std::vector<std::string> otcMapDraftIssueCodes;
    bool accountingEngineCalled = false;
    bool productionFileLoading = false;
    bool productionWrite = false;
    bool sqliteProductionWrite = false;
    bool auditWritten = false;
    bool ledgerWritten = false;
    bool snapshotWritten = false;
    bool tradeLogWritten = false;
    bool readModelPersistentWrite = false;
    bool networkAccess = false;
    bool credentialAccess = false;
    bool endpointAccess = false;
    bool automaticTrading = false;
    bool rawUserDataExposed = false;
};

[[nodiscard]] bool isShellAccountingServiceResultReadOnly(
    const ShellAccountingServiceResult& result) noexcept;

}  // namespace etfdt::shell_services
